Make location a struct
nextmv-io/nextroute pull request #43
Opened 2024-05-14 12:54 UTC by dirkschumacher

This improves efficiency by making the location a struct and also reduce its size (8 fewer bytes).

2024-05-14 13:39 UTC, davidrijsman requested changes
I would not do this. This will allow users to update a Location without us having any control on the values set. Today one can only create a location by invoking the factory method NewLocation which makes it very clear where values are set.

2024-05-14 13:48 UTC, dirkschumacher commented
> I would not do this. This will allow users to update a Location without us having any control on the values set. Today one can only create a location by invoking the factory method NewLocation which makes it very clear where values are set.

That's not true as the fields are private

```go
type Location struct {
	longitude float64
	latitude  float64
}
```

2024-05-14 13:51 UTC, davidrijsman approved these changes
As long as the properties of Location are not exported. Would be nice if this PR is actually also leveraging this change in the nextroute code.

2024-05-14 14:04 UTC, sebastian-quintero approved these changes
🌮

2024-05-14 14:53 UTC, dirkschumacher commented
> Would be nice if this PR is actually also leveraging this change in the nextroute code.

@davidrijsman can you elaborate a bit what you mean?

2024-05-15 20:18 UTC, larsbeck commented on solution_construcation_sweep_test.go
> +		Lat: 0,
Did this latitude change from being invalid to being valid? Before this PR it came from `common.NewInvalidLocation().Latitude()`. Now it is `0`. The comment on the new `IsValid` method says:
```
/ IsValid returns true if the location is valid. A location is valid if the
// longitude is between (-180, 180) and the latitude is between (-90, 90).
```

2024-05-15 20:20 UTC, dirkschumacher commented on solution_construcation_sweep_test.go
> +		Lat: 0,
@larsbeck the latitude/longitude of an invalid location has been 0/0 before with the `bool valid` field set to `false`. Now invalid locations have `NaN/NaN` as coordinate. So this code change is equivalent to what the test did before.

2024-05-15 20:27 UTC, larsbeck approved these changes

2024-05-17 09:47 UTC, dirkschumacher commented
For now I leave the size of the struct as is. It appears that this is the faster approach during the search as most time is spent on validating locations. We can revisit that later.

2024-05-17 09:47 UTC, merged